
import type { Metadata, Viewport } from "next";
import { Nunito } from "next/font/google";
import {ClerkProvider} from '@clerk/nextjs'

import "./globals.css";

const font = Nunito({ subsets: ["latin"] });

export const viewport: Viewport = {
  themeColor: "#22C55E",
};

export const metadata: Metadata = {
  title: "Lingo",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider appearance={{
      layout: {
        logoImageUrl: "/favicon.ico",
      },
      variables: {
        colorPrimary: "#22C55E",
      },
    }}>
      <html lang="en">
       <body className={font.className}>
        {children}
      </body>
    </html>
    </ClerkProvider>
  );
}
